import type { StoryTravelKnowledgeEntry } from "./storyTravelTypes";

/**
 * Curated factual grounding — do not invent venues. Prefer broad, verifiable anchors.
 * `relationship` must reflect how strong the claim is.
 */
export const STORY_TRAVEL_KNOWLEDGE: StoryTravelKnowledgeEntry[] = [
  {
    key: "eat_pray_love",
    sourceTitle: "Eat Pray Love",
    aliases: ["eat pray love", "elizabeth gilbert"],
    sourceType: "mixed",
    authorOrCreator: "Elizabeth Gilbert",
    countries: ["Italy", "Indonesia", "India"],
    cities: ["Rome", "Ubud"],
    themes: ["food", "wellness", "slow travel", "reflection"],
    experiences: [
      {
        title: "Rome — pleasure and everyday food culture",
        subtitle: "Book & film tone without scripting your meals",
        sourceTitle: "Eat Pray Love",
        sourceType: "mixed",
        authorOrCreator: "Elizabeth Gilbert",
        experienceType: "full_trip_inspiration",
        description:
          "Lean into Roman cafés, markets, and slow lunches — inspiration from the Italy chapter, grounded in real city food culture rather than a checklist.",
        destinationFit: "exact_city",
        confidence: "medium",
        locations: [
          {
            id: "rome-food-culture",
            name: "Historic centre — cafés & markets",
            city: "Rome",
            country: "Italy",
            description: "Neighbourhood food energy and trattoria culture (general area, not one branded venue).",
            relationship: "inspiration",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["food", "culture", "slow"],
        budgetFit: "mid",
        tags: ["food", "italy", "slow"],
        explanation: "A soft Eat Pray Love–style framing for Rome: food-forward, unhurried, and practical.",
        optional: true,
      },
      {
        title: "Ubud — slow Bali chapter mood",
        sourceTitle: "Eat Pray Love",
        sourceType: "mixed",
        experienceType: "landscape_vibe",
        description: "Rice terraces, slower pacing, and wellness-oriented days — keep claims modest and choose reputable studios if you book.",
        destinationFit: "exact_city",
        confidence: "medium",
        locations: [
          {
            id: "ubud-vibe",
            name: "Ubud countryside & town walks",
            city: "Ubud",
            country: "Indonesia",
            description: "Landscape and pacing inspiration from the memoir’s Bali section.",
            relationship: "vibe_match",
          },
        ],
        recommendedDuration: "full_day",
        bestFitForTravelStyles: ["culture", "slow"],
        budgetFit: "any",
        tags: ["wellness", "bali"],
        explanation: "Mood match for Ubud — not a map of fictional places.",
        optional: true,
      },
    ],
  },
  {
    key: "harry_potter",
    sourceTitle: "Harry Potter",
    aliases: ["harry potter", "hogwarts", "jk rowling"],
    sourceType: "mixed",
    authorOrCreator: "J.K. Rowling",
    countries: ["United Kingdom"],
    cities: ["London", "Oxford", "Edinburgh"],
    themes: ["fantasy", "film", "literary"],
    experiences: [
      {
        title: "London — King’s Cross & British Library energy",
        sourceTitle: "Harry Potter",
        sourceType: "mixed",
        experienceType: "themed_walk",
        description:
          "Public-facing touchpoints like King’s Cross (Platform 9¾ photo spot) and Victorian London street atmosphere — treat busy periods as a tradeoff.",
        destinationFit: "exact_city",
        confidence: "high",
        locations: [
          {
            id: "kings-cross",
            name: "King’s Cross Station area",
            city: "London",
            country: "United Kingdom",
            description: "Known public photo spot and surrounding streets.",
            relationship: "adaptation_related",
          },
        ],
        recommendedDuration: "quick_stop",
        bestFitForTravelStyles: ["culture"],
        budgetFit: "budget",
        tags: ["fantasy", "london"],
        explanation: "Compact Potter-adjacent London beat — mostly adaptation-adjacent public spaces.",
        optional: true,
      },
      {
        title: "Oxford — colleges & library atmosphere",
        sourceTitle: "Harry Potter",
        sourceType: "film",
        experienceType: "literary_route",
        description: "Oxford’s colleges and libraries influenced on-screen Hogwarts aesthetics — visit real colleges and museums, not private film sets.",
        destinationFit: "exact_city",
        confidence: "medium",
        locations: [
          {
            id: "oxford-colleges",
            name: "Oxford historic colleges (visitor routes)",
            city: "Oxford",
            country: "United Kingdom",
            description: "Public visitor routes vary by college — check opening hours.",
            relationship: "filming_location",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["culture"],
        budgetFit: "mid",
        tags: ["oxford", "film"],
        explanation: "Oxford as a credible Potter-adjacent day without promising interior film access.",
        optional: true,
      },
      {
        title: "Edinburgh — old town & literary cafés",
        sourceTitle: "Harry Potter",
        sourceType: "book",
        experienceType: "literary_route",
        description: "Edinburgh’s Old Town and café culture shaped early drafting — focus on literary history and city walks.",
        destinationFit: "exact_city",
        confidence: "medium",
        locations: [
          {
            id: "edinburgh-old-town",
            name: "Edinburgh Old Town",
            city: "Edinburgh",
            country: "United Kingdom",
            description: "Historic streets and viewpoints tied to the author’s time in the city.",
            relationship: "author_biographical",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["culture", "slow"],
        budgetFit: "mid",
        tags: ["edinburgh", "literary"],
        explanation: "Literary and biographical framing — not a studio tour.",
        optional: true,
      },
    ],
  },
  {
    key: "lotr",
    sourceTitle: "The Lord of the Rings",
    aliases: ["lotr", "lord of the rings", "tolkien", "middle earth"],
    sourceType: "mixed",
    authorOrCreator: "J.R.R. Tolkien",
    countries: ["New Zealand", "United Kingdom"],
    cities: ["Matamata", "Wellington", "Queenstown", "Oxford"],
    themes: ["landscape", "film", "literary"],
    experiences: [
      {
        title: "New Zealand — Hobbiton & Central Otago landscapes",
        sourceTitle: "The Lord of the Rings",
        sourceType: "film",
        experienceType: "filming_location",
        description: "Hobbiton movie set visits (book ahead) plus South Island landscape corridors used on screen.",
        destinationFit: "country",
        confidence: "high",
        locations: [
          {
            id: "hobbiton",
            name: "Hobbiton Movie Set (Matamata)",
            city: "Matamata",
            country: "New Zealand",
            description: "Ticketed film location — confirm schedules.",
            relationship: "filming_location",
          },
          {
            id: "queenstown-landscape",
            name: "Queenstown region landscapes",
            city: "Queenstown",
            country: "New Zealand",
            description: "High-confidence landscape corridor vibes; exact shot spots vary.",
            relationship: "filming_location",
          },
        ],
        recommendedDuration: "multi_day",
        bestFitForTravelStyles: ["culture", "slow"],
        budgetFit: "premium",
        tags: ["new zealand", "film"],
        explanation: "NZ as the flagship LOTR filming geography — still respect driving distances.",
        optional: true,
      },
      {
        title: "Oxford — Tolkien & Inklings literary footprint",
        sourceTitle: "The Lord of the Rings",
        sourceType: "book",
        experienceType: "author_place",
        description: "Colleges, pubs, and museum collections associated with Tolkien’s Oxford years — public walking context only.",
        destinationFit: "exact_city",
        confidence: "medium",
        locations: [
          {
            id: "oxford-tolkien",
            name: "Oxford — Inklings-adjacent public walk",
            city: "Oxford",
            country: "United Kingdom",
            description: "Biographical and literary context; no private interior guarantees.",
            relationship: "author_biographical",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["culture"],
        budgetFit: "mid",
        tags: ["oxford", "literary"],
        explanation: "Literary route separate from NZ filming geography.",
        optional: true,
      },
    ],
  },
  {
    key: "got",
    sourceTitle: "Game of Thrones",
    aliases: ["game of thrones", "got", "king's landing"],
    sourceType: "series",
    countries: ["Croatia", "United Kingdom", "Spain"],
    cities: ["Dubrovnik", "Split", "Belfast", "Girona"],
    themes: ["film", "medieval"],
    experiences: [
      {
        title: "Dubrovnik — King’s Landing filming walk",
        sourceTitle: "Game of Thrones",
        sourceType: "series",
        experienceType: "themed_walk",
        description: "Old Town walls and streets widely used on screen — expect crowds; combine with normal Dubrovnik pacing.",
        destinationFit: "exact_city",
        confidence: "high",
        locations: [
          {
            id: "dubrovnik-old-town",
            name: "Dubrovnik Old Town",
            city: "Dubrovnik",
            country: "Croatia",
            description: "Extensively filmed historic core.",
            relationship: "filming_location",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["culture"],
        budgetFit: "mid",
        tags: ["croatia", "dubrovnik"],
        explanation: "Strong destination match when you are already in Dubrovnik.",
        optional: true,
      },
      {
        title: "Northern Ireland — coastal filming corridor",
        sourceTitle: "Game of Thrones",
        sourceType: "series",
        experienceType: "landscape_vibe",
        description: "Publicly promoted filming trails exist — use official tourism routes; weather and closures vary.",
        destinationFit: "regional",
        confidence: "medium",
        locations: [
          {
            id: "ni-film-trail",
            name: "Causeway Coast filming trail (region)",
            region: "Northern Ireland",
            country: "United Kingdom",
            description: "Regional corridor — plan as a dedicated day if you include it.",
            relationship: "filming_location",
          },
        ],
        recommendedDuration: "full_day",
        bestFitForTravelStyles: ["culture", "slow"],
        budgetFit: "mid",
        tags: ["northern ireland"],
        explanation: "Regional filming geography — not a single street stop.",
        optional: true,
      },
    ],
  },
  {
    key: "ghibli",
    sourceTitle: "Studio Ghibli",
    aliases: ["ghibli", "miyazaki", "spirited away"],
    sourceType: "film",
    countries: ["Japan"],
    cities: ["Tokyo", "Mitaka", "Nagoya"],
    themes: ["anime", "slow", "nature"],
    experiences: [
      {
        title: "Mitaka — Ghibli Museum (ticketed)",
        sourceTitle: "Studio Ghibli",
        sourceType: "film",
        experienceType: "museum",
        description: "Small, ticket-limited museum — plan reservations far ahead; not a full-park experience.",
        destinationFit: "exact_city",
        confidence: "high",
        locations: [
          {
            id: "ghibli-museum",
            name: "Ghibli Museum, Mitaka",
            city: "Mitaka",
            country: "Japan",
            description: "Official museum — timed entry.",
            relationship: "confirmed_location",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["culture", "slow"],
        budgetFit: "mid",
        tags: ["tokyo", "museum"],
        explanation: "High-confidence exact venue — still subject to ticketing reality.",
        optional: true,
      },
      {
        title: "Japan — Ghibli-like pacing & nature corridors",
        sourceTitle: "Studio Ghibli",
        sourceType: "film",
        experienceType: "landscape_vibe",
        description: "Slow trains, neighbourhood shrines, and green corridors that echo Ghibli pacing — label as vibe, not shot-for-shot.",
        destinationFit: "country",
        confidence: "low",
        locations: [
          {
            id: "japan-vibe",
            name: "Urban + fringe nature mix",
            country: "Japan",
            description: "Mood-led suggestions only — pair with your real route.",
            relationship: "vibe_match",
          },
        ],
        recommendedDuration: "full_day",
        bestFitForTravelStyles: ["slow", "culture"],
        budgetFit: "any",
        tags: ["japan", "slow"],
        explanation: "Explicit vibe match — not claiming specific fictional locations.",
        optional: true,
      },
    ],
  },
  {
    key: "kafka",
    sourceTitle: "Franz Kafka",
    aliases: ["kafka", "metamorphosis"],
    sourceType: "author",
    authorOrCreator: "Franz Kafka",
    countries: ["Czech Republic"],
    cities: ["Prague"],
    themes: ["literary", "museum"],
    experiences: [
      {
        title: "Prague — Kafka Museum & Old Town literary walk",
        sourceTitle: "Franz Kafka",
        sourceType: "author",
        experienceType: "literary_route",
        description: "Museum visit plus compact Old Town walk — keep claims to established public sites.",
        destinationFit: "exact_city",
        confidence: "high",
        locations: [
          {
            id: "kafka-museum",
            name: "Kafka Museum",
            city: "Prague",
            country: "Czech Republic",
            description: "Dedicated museum in Malá Strana.",
            relationship: "confirmed_location",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["culture"],
        budgetFit: "mid",
        tags: ["prague", "literary"],
        explanation: "Strong author-city pairing.",
        optional: true,
      },
    ],
  },
  {
    key: "joyce",
    sourceTitle: "James Joyce / Ulysses",
    aliases: ["ulysses", "james joyce", "bloomsday"],
    sourceType: "author",
    authorOrCreator: "James Joyce",
    countries: ["Ireland"],
    cities: ["Dublin"],
    themes: ["literary"],
    experiences: [
      {
        title: "Dublin — Bloomsday-friendly literary walk",
        sourceTitle: "Ulysses",
        sourceType: "book",
        experienceType: "literary_route",
        description: "Temple Bar edges, Trinity area, and river walks often used on literary tours — no need to over-script every stop.",
        destinationFit: "exact_city",
        confidence: "medium",
        locations: [
          {
            id: "dublin-river",
            name: "River Liffey corridors & city centre",
            city: "Dublin",
            country: "Ireland",
            description: "Public literary walking context.",
            relationship: "inspiration",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["culture", "slow"],
        budgetFit: "budget",
        tags: ["dublin", "literary"],
        explanation: "Joyce framing for Dublin without inventing private interiors.",
        optional: true,
      },
    ],
  },
  {
    key: "hemingway",
    sourceTitle: "Ernest Hemingway",
    aliases: ["hemingway", "moveable feast"],
    sourceType: "author",
    authorOrCreator: "Ernest Hemingway",
    countries: ["France", "United States"],
    cities: ["Paris", "Key West"],
    themes: ["literary", "cafe"],
    experiences: [
      {
        title: "Paris — Left Bank café literary stroll",
        sourceTitle: "Ernest Hemingway",
        sourceType: "author",
        experienceType: "literary_route",
        description: "Café culture and boulevard walks in the spirit of A Moveable Feast — keep recommendations general.",
        destinationFit: "exact_city",
        confidence: "medium",
        locations: [
          {
            id: "paris-left-bank",
            name: "Saint-Germain-des-Prés area",
            city: "Paris",
            country: "France",
            description: "Historic café quarter — specific venues change; verify hours.",
            relationship: "inspiration",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["culture", "food"],
        budgetFit: "mid",
        tags: ["paris", "cafe"],
        explanation: "Mood-led Paris beat — not a fixed venue list.",
        optional: true,
      },
      {
        title: "Key West — Hemingway Home",
        sourceTitle: "Ernest Hemingway",
        sourceType: "author",
        experienceType: "author_place",
        description: "Ticketed house museum — check hours and heat; small, focused visit.",
        destinationFit: "exact_city",
        confidence: "high",
        locations: [
          {
            id: "hemingway-home",
            name: "The Hemingway Home and Museum",
            city: "Key West",
            country: "United States",
            description: "Established biographical site.",
            relationship: "confirmed_location",
          },
        ],
        recommendedDuration: "quick_stop",
        bestFitForTravelStyles: ["culture"],
        budgetFit: "mid",
        tags: ["key west"],
        explanation: "Exact biographical venue when you are in Key West.",
        optional: true,
      },
    ],
  },
  {
    key: "shakespeare",
    sourceTitle: "William Shakespeare",
    aliases: ["shakespeare", "globe theatre"],
    sourceType: "author",
    authorOrCreator: "William Shakespeare",
    countries: ["United Kingdom"],
    cities: ["London", "Stratford-upon-Avon"],
    themes: ["theatre", "literary"],
    experiences: [
      {
        title: "London — Shakespeare’s Globe",
        sourceTitle: "William Shakespeare",
        sourceType: "author",
        experienceType: "museum",
        description: "Working reconstruction theatre — performances and tours depend on season.",
        destinationFit: "exact_city",
        confidence: "high",
        locations: [
          {
            id: "globe-london",
            name: "Shakespeare's Globe",
            city: "London",
            country: "United Kingdom",
            description: "Southbank theatre and exhibition spaces.",
            relationship: "confirmed_location",
          },
        ],
        recommendedDuration: "half_day",
        bestFitForTravelStyles: ["culture"],
        budgetFit: "mid",
        tags: ["london", "theatre"],
        explanation: "High-confidence theatre anchor in London.",
        optional: true,
      },
      {
        title: "Stratford-upon-Avon — Shakespeare birthplace town",
        sourceTitle: "William Shakespeare",
        sourceType: "author",
        experienceType: "literary_route",
        description: "Compact town with multiple Shakespeare trusts sites — choose 1–2 to avoid museum fatigue.",
        destinationFit: "exact_city",
        confidence: "high",
        locations: [
          {
            id: "stratford-town",
            name: "Stratford-upon-Avon town centre",
            city: "Stratford-upon-Avon",
            country: "United Kingdom",
            description: "Cluster of established heritage sites.",
            relationship: "author_biographical",
          },
        ],
        recommendedDuration: "full_day",
        bestFitForTravelStyles: ["culture"],
        budgetFit: "mid",
        tags: ["stratford"],
        explanation: "Strong author-town pairing.",
        optional: true,
      },
    ],
  },
  {
    key: "sherlock",
    sourceTitle: "Sherlock Holmes",
    aliases: ["sherlock holmes", "sherlock", "baker street"],
    sourceType: "book",
    countries: ["United Kingdom"],
    cities: ["London"],
    themes: ["literary", "museum"],
    experiences: [
      {
        title: "London — Baker Street museum & Victorian walk",
        sourceTitle: "Sherlock Holmes",
        sourceType: "book",
        experienceType: "themed_walk",
        description: "Small museum near Baker Street plus Marylebone Victorian streetscape — keep expectations museum-sized.",
        destinationFit: "exact_city",
        confidence: "high",
        locations: [
          {
            id: "sherlock-museum",
            name: "Sherlock Holmes Museum",
            city: "London",
            country: "United Kingdom",
            description: "Ticketed small museum.",
            relationship: "confirmed_location",
          },
        ],
        recommendedDuration: "quick_stop",
        bestFitForTravelStyles: ["culture"],
        budgetFit: "budget",
        tags: ["london", "detective"],
        explanation: "Compact London add-on when you already pass nearby.",
        optional: true,
      },
    ],
  },
];
