import type { Achievement } from "./achievement.types";

/**
 * Central catalog of achievements (code-only). New rows only need new entries here;
 * Firestore progress docs stay `{ achievementKey, progress, target, unlocked, ... }`.
 *
 * Keep rewards tied to real travel outcomes — see `./gamificationConstraints` (no ranking/feasibility coupling).
 */
export const ACHIEVEMENT_DEFINITIONS: readonly Achievement[] = [
  {
    id: "first_trip_completed",
    key: "first_trip_completed",
    title: "First Trip Completed",
    description: "Fully complete your first trip.",
    category: "travel",
    icon: "flag",
    evaluationSignals: ["completedTrip"],
    conditions: [{ type: "trips_completed", target: 1 }],
  },
  {
    id: "five_trips_completed",
    key: "five_trips_completed",
    title: "5 Trips Completed",
    description: "Fully complete five trips.",
    category: "travel",
    icon: "format_list_numbered",
    evaluationSignals: ["completedTrip"],
    conditions: [{ type: "trips_completed", target: 5 }],
  },
  {
    id: "ten_trips_completed",
    key: "ten_trips_completed",
    title: "10 Trips Completed",
    description: "Fully complete ten trips.",
    category: "travel",
    icon: "military_tech",
    evaluationSignals: ["completedTrip"],
    conditions: [{ type: "trips_completed", target: 10 }],
  },
  {
    id: "visit_three_cities",
    key: "visit_three_cities",
    title: "Visit 3 Cities",
    description: "Complete at least one activity in three different cities.",
    category: "exploration",
    icon: "location_city",
    evaluationSignals: ["completedItem", "completedTrip"],
    conditions: [{ type: "cities_visited", target: 3 }],
  },
  {
    id: "visit_ten_cities",
    key: "visit_ten_cities",
    title: "Visit 10 Cities",
    description: "Complete at least one activity in ten different cities.",
    category: "exploration",
    icon: "map",
    evaluationSignals: ["completedItem", "completedTrip"],
    conditions: [{ type: "cities_visited", target: 10 }],
  },
  {
    id: "visit_two_countries",
    key: "visit_two_countries",
    title: "Visit 2 Countries",
    description: "Complete at least one activity in two different countries.",
    category: "exploration",
    icon: "public",
    evaluationSignals: ["completedItem", "completedTrip"],
    conditions: [{ type: "countries_visited", target: 2 }],
  },
  {
    id: "visit_five_countries",
    key: "visit_five_countries",
    title: "Visit 5 Countries",
    description: "Complete at least one activity in five different countries.",
    category: "exploration",
    icon: "travel_explore",
    evaluationSignals: ["completedItem", "completedTrip"],
    conditions: [{ type: "countries_visited", target: 5 }],
  },
  {
    id: "bucket_five_completed",
    key: "bucket_five_completed",
    title: "Complete 5 Bucket List Items",
    description: "Mark five bucket list places as visited.",
    category: "consistency",
    icon: "checklist",
    evaluationSignals: ["updatedBucketList"],
    conditions: [{ type: "bucket_items_completed", target: 5 }],
  },
  {
    id: "bucket_twenty_completed",
    key: "bucket_twenty_completed",
    title: "Complete 20 Bucket List Items",
    description: "Mark twenty bucket list places as visited.",
    category: "consistency",
    icon: "playlist_add_check",
    evaluationSignals: ["updatedBucketList"],
    conditions: [{ type: "bucket_items_completed", target: 20 }],
  },
  {
    id: "bucket_collector_ten",
    key: "bucket_collector_ten",
    title: "Collector",
    description: "Save ten distinct places on your bucket list.",
    category: "exploration",
    icon: "playlist_add_check",
    evaluationSignals: ["updatedBucketList"],
    conditions: [{ type: "bucket_places_collected", target: 10 }],
  },
  {
    id: "bucket_collector_twenty_five",
    key: "bucket_collector_twenty_five",
    title: "Curator",
    description: "Save twenty-five distinct places on your bucket list.",
    category: "exploration",
    icon: "travel_explore",
    evaluationSignals: ["updatedBucketList"],
    conditions: [{ type: "bucket_places_collected", target: 25 }],
  },
  {
    id: "high_completion_one_trip_90",
    key: "high_completion_one_trip_90",
    title: "High Completion Rate",
    description: "Finish a completed trip with at least 90% of planned items done.",
    category: "challenge",
    icon: "trending_up",
    evaluationSignals: ["completedItem", "completedTrip"],
    conditions: [{ type: "best_trip_completion_rate", threshold: 0.9 }],
  },
  {
    id: "consistent_traveler_80_three",
    key: "consistent_traveler_80_three",
    title: "Consistent Traveler",
    description: "Fully complete three trips, each with at least 80% of planned items done.",
    category: "consistency",
    icon: "repeat",
    evaluationSignals: ["completedItem", "completedTrip"],
    conditions: [{ type: "trips_above_completion_rate_count", threshold: 0.8, minTrips: 3 }],
  },
  {
    id: "explorer_five_categories",
    key: "explorer_five_categories",
    title: "Explorer",
    description: "Complete activities across five different categories.",
    category: "exploration",
    icon: "category",
    evaluationSignals: ["completedItem", "completedTrip"],
    conditions: [{ type: "unique_categories", target: 5 }],
  },
  {
    id: "food_explorer_ten",
    key: "food_explorer_ten",
    title: "Food Explorer",
    description: "Complete ten food-related activities.",
    category: "exploration",
    icon: "restaurant",
    evaluationSignals: ["completedItem", "completedTrip"],
    conditions: [{ type: "food_related_visits", target: 10 }],
  },
  {
    id: "efficient_traveler_low_delay",
    key: "efficient_traveler_low_delay",
    title: "Efficient Traveler",
    description: "Complete a trip with strong on-time execution: no travel-delay days, high completion, and low average start delay when timings were logged.",
    category: "challenge",
    icon: "schedule",
    evaluationSignals: ["completedItem", "completedTrip"],
    conditions: [
      {
        type: "efficient_completed_trip",
        minCompletionRate: 0.85,
        maxAverageStartDelayMinutes: 15,
        maxTravelDelayDays: 0,
      },
    ],
  },
];
